### ISSUE TITLE
Add Google Gemini as an option

### ISSUE THREAD

**Issue by karan** [sakowicz/actual-ai#49]
Should we pretty straightforward:

- Add the following config options and env vars: `GOOGLE_GEMINI_API_KEY`, `GOOGLE_GEMINI_MODEL` (default to `gemini-1.5-flash`).
- Rename `openai.js` to something like `llm.js` and implement a `callGoogle` function (reference: https://ai.google.dev/gemini-api/docs#node.js).

I can also send a PR if I can get node to work properly on my setup (libnode just doesn't seem to work for some reason).

**Comment by sakowicz** [comment]
Check out the latest release, and let me know if everything works!
