### ISSUE TITLE
All non-default model calls to OpenAI come back invalid

### ISSUE THREAD

**Issue by trashdad** [sakowicz/actual-ai#51]
![image](https://github.com/user-attachments/assets/6d37789a-bbc1-4282-a82f-09bc5d569c9e)

have tried:

Specifying any model using the OPENAI_MODEL env variable results in an error.

I have credits on my account, it is not registering activity to my API

**Comment by sakowicz** [comment]
Hello!

Can you try without `"`?

**Comment by trashdad** [comment]
> Hello!
> 
> Can you try without `"`?

I have amended my initial post. If OPENAI_MODEL is commented out, it defaults to gpt-4-turbo as expected. Specifying any other model (gpt-4o, gpt-4-mini, etc.) results in an error.

I have tried with and without the ""

**Comment by sakowicz** [comment]
https://platform.openai.com/docs/models

There is no `gpt-4-mini` model; maybe you mean `gpt-4o-mini`?

`gpt-4o` works for me 🤔 

Can you show me how you set that model?

**Comment by trashdad** [comment]
> https://platform.openai.com/docs/models
> 
> There is no `gpt-4-mini` model; maybe you mean `gpt-4o-mini`?
> 
> `gpt-4o` works for me 🤔
> 
> Can you show me how you set that model?

That must have been my problem. Simply not copying down the model names down correctly, or using "" inappropriately. 

Sorry for wasting your time, I tried `gpt-4o-mini` and it works just fine.
